'use client';
import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';

type Profile = { thc?: number|null; cbd?: number|null; cbg?: number|null; other?: string|null };
type Product = { id:string; name:string; nfcId:string; sku?:string|null; description?:string|null; createdAt:string; brand:{name:string; logoUrl?:string|null}; cannabinoidProfile?:Profile|null; terpeneProfile?:{data:string}|null; media:{url:string; altText?:string|null}[]; coa?:{url:string;labName?:string|null;testDate?:string|null}|null; _count:{scans:number} };
const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
const fmt=(v?:string|null)=>v?new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
function Bars({ title, values }: { title:string; values:Record<string, number> }) { const entries=Object.entries(values).filter(([,v])=>v>0); return <section className="glass rounded-2xl p-5"><h2 className="mb-5 text-lg font-semibold">{title}</h2><div className="space-y-4">{entries.length?entries.map(([name,value])=><div key={name}><div className="mb-1 flex justify-between text-xs text-[#B8B1BA]"><span>{name}</span><span>{value.toFixed(2)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#D9A441] to-[#E7B95A]" style={{width:`${Math.min(100,value)}%`}}/></div></div>):<p className="text-sm text-[#7F7885]">No profile data available.</p>}</div></section> }
function Skeleton(){return <main className="mx-auto max-w-md space-y-4 p-5"><div className="h-10 w-40 animate-pulse rounded-xl bg-white/10"/><div className="h-72 animate-pulse rounded-2xl bg-white/10"/>{[1,2,3].map(i=><div key={i} className="h-32 animate-pulse rounded-2xl bg-white/10"/>)}</main>}
export default function TapPage(){const {nfcId}=useParams<{nfcId:string}>(); const [product,setProduct]=useState<Product|null>(null); const [error,setError]=useState(false); const [chat,setChat]=useState(false); const [text,setText]=useState(''); const [messages,setMessages]=useState<string[]>(['👋 Hi! I\'m your Cannect budtender. Ask me anything about this product!']); const [copied,setCopied]=useState(false);
 useEffect(()=>{fetch(`${API}/api/tap/${encodeURIComponent(nfcId)}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(setProduct).catch(()=>setError(true))},[nfcId]);
 const terpenes=useMemo(()=>{try{return product?.terpeneProfile?.data?JSON.parse(product.terpeneProfile.data):{}}catch{return {}}},[product]);
 if(!product&&!error)return <Skeleton/>; if(error)return <main className="flex min-h-dvh items-center justify-center p-5"><div className="glass rounded-2xl p-8 text-center"><div className="mb-4 text-4xl">◌</div><h1 className="text-2xl font-semibold">Product not found</h1><p className="mt-2 text-sm text-[#B8B1BA]">This NFC tag doesn&apos;t match any product in our system.</p></div></main>;
 const c=product!.cannabinoidProfile||{}; const share=()=>{navigator.clipboard?.writeText(window.location.href);setCopied(true);setTimeout(()=>setCopied(false),2500)}; const send=()=>{if(text.trim()){setMessages(m=>[...m, text.trim()]);setText('')}};
 return <main className="min-h-dvh bg-[#0B0A0F] pb-28"><div className="mx-auto max-w-md space-y-4 px-5 py-5"><header className="flex items-center justify-between"><span className="font-semibold tracking-[.22em] text-[#F6F1E8]">CANNect</span><button onClick={share} className="glass rounded-full px-4 py-2 text-xs text-[#D9A441]">{copied?'Link copied!':'Share'}</button></header>
 <section className="glass rounded-2xl border-[#78C6A3]/40 p-4"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#78C6A3]/15 text-xl text-[#78C6A3]">✓</div><div><p className="font-semibold text-[#78C6A3]">Verified Authentic</p><p className="text-xs text-[#B8B1BA]">Powered by Cannect</p></div><span className="ml-auto text-right text-xs text-[#B8B1BA]">Scanned<br/><b className="text-[#F6F1E8]">{product!._count.scans} times</b></span></div></section>
 <section className="glass overflow-hidden rounded-2xl"><div className="h-64 bg-cover bg-center" style={{backgroundImage:product!.media[0]?.url?`url(${product!.media[0].url})`:'linear-gradient(135deg,#17111E,#241A18)'}}/><div className="p-5"><p className="text-xs uppercase tracking-[.15em] text-[#D9A441]">Digital product passport</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#F6F1E8]">{product!.name}</h1><p className="mt-1 text-[#B8B1BA]">{product!.brand.name} · {product!.sku||'Batch verified'}</p><div className="mt-5 grid grid-cols-3 gap-2">{[['THC',c.thc],['CBD',c.cbd],['Batch',product!.sku||'—']].map(([k,v])=><div key={k} className="rounded-xl bg-white/[.06] p-3"><p className="text-[10px] uppercase tracking-wider text-[#7F7885]">{k}</p><p className="mt-1 truncate text-sm font-semibold text-[#F6F1E8]">{typeof v==='number'?`${v}%`:v}</p></div>)}</div></div></section>
 <Bars title="Cannabinoid profile" values={{THC:c.thc||0,CBD:c.cbd||0,CBG:c.cbg||0}}/><Bars title="Terpene profile" values={terpenes}/>
 <section className="glass rounded-2xl p-5"><h2 className="text-lg font-semibold">COA / Lab results</h2><p className="mt-3 text-sm text-[#B8B1BA]">{product!.coa?.labName||'Laboratory report'} · Tested {fmt(product!.coa?.testDate)}</p>{product!.coa?.url&&<a target="_blank" rel="noreferrer" href={product!.coa.url} className="mt-4 inline-flex rounded-xl bg-[#D9A441] px-4 py-3 text-sm font-semibold text-[#1A1207]">View Full COA ↗</a>}</section>
 <section className="glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Cultivation details</h2><p className="mt-3 text-sm text-[#B8B1BA]">Grower and origin details are maintained by {product!.brand.name}.</p><p className="mt-2 text-xs text-[#7F7885]">Passport record created {fmt(product!.createdAt)}</p></section>
 <section className="glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Effects &amp; flavors</h2><p className="mt-4 text-xs uppercase tracking-wider text-[#B8B1BA]">Reported Effects</p><div className="mt-2 flex flex-wrap gap-2"><span className="rounded-full border border-[#D9A441]/50 px-3 py-1 text-xs text-[#D9A441]">Explore the profile</span></div><p className="mt-4 text-xs uppercase tracking-wider text-[#B8B1BA]">Flavor Profile</p><p className="mt-2 text-sm text-[#7F7885]">See the terpene profile above for batch aroma data.</p></section>
 <footer className="py-5 text-center text-xs text-[#7F7885]">CANNect · <span className="text-[#B8B1BA]">Powered by Cannect</span></footer></div>
 <button aria-label="Ask the Budtender" onClick={()=>setChat(true)} className="fixed bottom-5 right-5 z-20 rounded-full bg-[#8D72B8] px-5 py-4 text-sm font-semibold text-white shadow-2xl">✦ Ask the Budtender</button>
 {chat&&<div className="fixed inset-0 z-30 flex items-end justify-center bg-black/70"><div className="glass-strong w-full max-w-md rounded-t-3xl p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Ask the Budtender</h2><button onClick={()=>setChat(false)} className="h-11 w-11 text-xl" aria-label="Close chat">×</button></div><p className="mb-4 text-xs text-[#B8B1BA]">General product information, not medical advice.</p><div className="max-h-64 space-y-2 overflow-auto">{messages.map((m,i)=><p key={i} className="rounded-xl bg-white/[.07] p-3 text-sm">{m}</p>)}</div><div className="mt-4 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about this product" className="h-11 min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[.05] px-3 text-sm outline-none"/><button onClick={send} className="rounded-xl bg-[#D9A441] px-4 text-sm font-semibold text-[#1A1207]">Send</button></div></div></div>}</main> }
